api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity', '%kernel.project_dir%/vendor/studentbundle/student-bundle/DTO']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
