services:

    _defaults:
        autowire: true
        autoconfigure: true

    StudentBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity}'

    StudentBundle\Service\ClearCacheService:
        arguments:
            $cache: '@redis_adapter'

    StudentBundle\EventListener\ClearCacheSubscriber:
        tags:
            - name: 'doctrine.event_subscriber'

    StudentBundle\Service\AggregationService:
        arguments:
            $cache: '@redis_adapter'

    old_sound_rabbit_mq.rating_producer:
        class: OldSound\RabbitMqBundle\RabbitMq\Producer

    # OldSound\RabbitMqBundle\RabbitMq\ProducerInterface: '@old_sound_rabbit_mq.rating_producer'

    StudentBundle\Service\AsyncService:
        calls:
            - ['registerProducer', [!php/const StudentBundle\Service\AsyncService::RATING, '@old_sound_rabbit_mq.rating_producer']]

    StudentBundle\Persister\RatingPersister: ~
