services:

    _defaults:
        autowire: true
        autoconfigure: true

    StudentBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity}'

    StudentBundle\Service\ClearCacheService:
        arguments:
            $cache: '@redis_adapter'
